### ISSUE TITLE
Historical Performance

### ISSUE THREAD

**Issue by vladiki** [christopherjenness/NBA-prediction#1]
Hello

This looks like a really cool project and a novel approach to this problem. Do you have any results to report on how accurate this method is for historical data?

**Comment by christopherjenness** [comment]
Not yet.  This weekend I'm going to sit down and do some back-testing.   One can easily leave values out of the known matrix, and see how well they are predicted in the rank-reduced SVD matrix.    I can say, however, that I have tested it against the last ~100 or so games, and I've beat the line about 73% of the time so far.  

Thanks for the feedback!

**Comment by vladiki** [comment]
That's awesome. I think the consensus is that the naive baseline (predicting home team to win every time) is 60% and state-of-the-art (using vegas line) is ~70%. Would also be interesting to see how this performs not only picking winners, but versus the o/u line.

**Comment by christopherjenness** [comment]
Oh, sorry.  I meant, I've been putting it against the spread (not just picking the winners).  Although, I have been accurately predicted a few upsets, which has been nice!

To be honest, the 73% will likely drop.  I can't image it preforms that well asymptotically.

**Comment by vladiki** [comment]
Oh in that case 73% is even more impressive. Does this approach extend to more dimensions as opposed to just OR and Pace?

**Comment by christopherjenness** [comment]
The method (SVD Factorization with rank reduction) is completely blind to what metric you are putting in. Here, I used pace and OR, but there is no reason why whatever incomplete matrix you wanted to look at couldn't be inputed.

**Comment by christopherjenness** [comment]
Added cross_val.R
