### ISSUE TITLE
Can't run model without predictions.csv

### ISSUE THREAD

**Issue by mamcmanus** [christopherjenness/NBA-prediction#3]
Hi! I'm trying to use your model - very cool work - but can't initialize the object without a predictions.csv file. Is that something I need to manually pull before running?

**Comment by christopherjenness** [comment]
Hi, this is a common problem people are reporting.  Preidctions.csv is written when you initialize the model with update=True.  I put that in the sample code in the readme, but I should probably change the sample code at the bottom of the script so people understand.  Thanks!

**Comment by vladiki** [comment]
In model.py you should instantiate the class with update=True. It'll pull down the latest data and generate the right files. You may also need to install a couple packages for R to get it to run correctly

**Comment by christopherjenness** [comment]
Oh, thanks vladiki, I forgot I used some R packages.  I'll add that to the readme.

**Comment by mamcmanus** [comment]
A requirements.txt file would be great, too!

**Comment by christopherjenness** [comment]
Yeah, I just pushed the requirements.txt.  Not familiar with the idiomatic way to specify which R packages are used though..
