### ISSUE TITLE
Updates to basketball-reference layout

### ISSUE THREAD

**Issue by swagdaddyflex6969** [christopherjenness/NBA-prediction#9]
nevermind

**Comment by amateursamurai** [comment]
In the code below updating -5 to -17 gets four factors, but if a game goes to OT for each OT, -2 must be added. ex. OT -> -19, 2OT ->-21, 3OT-> -23. 



def get_stats(self, url):
        """
        Extracts statistics from URL
        Args:
            url (str): basketball-reference.com box score
        Returns:
            stats (pd.DataFrame): DataFrame of statistics from game
        """
        response = urlopen(url)
        html = response.read()
        html = html.decode("utf8")
        stat_html = html.replace('', "")
        stats = pd.read_html(stat_html)
        **return stats[-17]**
